---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by v_chaodchen.
--- DateTime: 2023/6/15 14:48
---

local version = "0.1.1"
local name = "AutoLua"

function main()
    Log:d("lua", "welcome to AutoLua.")
    Log:d("lua","version" .. version)
    Log:d("lua","name" .. name)
    local test = Auto:findAccessibilityNodeByText("微信")
    if (test ~= nil) then
        Log:d("lua", "找到了")
    else
        Log:d("lua", "没找到")
    end
end

main()